### ISSUE TITLE
Cuando actualicemos CKAN los estilos se van a romper

### ISSUE THREAD

**Issue by rodowi** [mxabierto/devops#2]
Dado que eventualmente reemplazaremos el backend de CKAN con ADELA, creo que este problema lo podemos resolver con los siguientes escenarios:

1. Dedicarnos a arreglar el estilo
2. Mandar a la shhht el estilo y deshabilitar la vista web de CKAN, para sólo usar el API. Ya que el front lo reemplaza busca.datos.gob.mx (github.com/mxabierto/ng-ckan)

**Comment by urkonn** [comment]
nos quedamos con la opción 2
