### ISSUE TITLE
Plan para el cluster

### ISSUE THREAD

**Issue by urkonn** [mxabierto/devops#3]
Reunirnos el martes 8 o miércoles 9 de diciembre
@bcessa @rodowi

**Comment by rodowi** [comment]
Checklist:

- [ ] conseguir acceso VPN
- [ ] checar discoverability de todas las VMs
- [ ] validar que docker está instalado
- [ ] instalar fleetctl
- [ ] ...

**Comment by rodowi** [comment]
Será conveniente mantener unas semanas activos tanto el cluster como los VPS actuales? Se me ocurre que podríamos tener Load-balanceados los servicios viejos y nuevos, y medir con New Relic nuestro SLA. Y ya que estemos seguros que todo está en orden, cortamos el servicio viejo.

**Comment by rodowi** [comment]
Sería buena idea trabajar sobre https://github.com/mxabierto/cluster para tener un ambiente virtualizado de prueba con el setup.

**Comment by rodowi** [comment]
La discusión se movió a: https://docs.google.com/document/d/1E9nzvJUXEkh3hcaJ_ekfbiszkj75w3rZF0ijDFUHtBY/edit
